name: Build Java Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: mvn clean package -Pproduction

      - run: cp target/*.jar ./app.jar

      - uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: app.jar
